### ISSUE TITLE
No match  keywords-a match outcome in Meta_info.json 

### ISSUE THREAD

**Issue by Lockjava** [asmerdov/eSports_Sensors_Dataset#1]
Hello,i can't find the match outcome in Meta_info.json，and can you  tell me where it is?

**Comment by smerdov** [comment]
Hi! Please find match outcome in `replay.json` file. The result for participants is available under keys `["teams"]["participants"]["win"]`, result for opponents - under `["teams"]["opponents"]["win"]`.

**Comment by Lockjava** [comment]
Ok,thanks
